# Maintenance gate
maintenance_entrance: {'62': 1, '143': 0}
maintenance_path: {'157': 1, '66': 0,'136': 2, '58': 1, '63': 0, '68': 2,'62': 1, '143': 0}
maintenance_exit: {'135': [1,2]}
maintenance_intersection: {'tag': 261}


# General path back to city
path_to_city: {'238': 1, '144':2, '260': 2, '149': 0, '153': 1, '237': 1, '236': 0, '242': 0, '61': 1}

# Charging station
charging_stations:
  stop_signs: {'tag': [190, 193, 37, 194]}
  station1:
    path_in: {'261': 1, '235': 2, '240': 1}
    path_calib: {'144': 2, '260': 1}
  station2:
    path_in: {'261': 2, '240': 0, '235': 1}
    path_calib: {'236': 0, '153': 0, '243': 2}
  station3:
    path_in: {'261': 1, '235': 1, '240': 1}
    path_calib: {'238': 1, '260': 1}
  station4:
    path_in: {'261': 2, '240': 1, '235': 1}
    path_calib: {'237': 1, '153': 0, '243': 2}
  entrances: {'235': [1,2], '240': [0,1]}
  exits: {'144': [0,2], 236': [0,2], '238': [1,2], '237': [0,1]}

# Calibration station
calibration_station:
  entrances: {'243': 2, '260': 1}
  exits: {'242': [0,1]}
